[package]
name = "bevy_editor"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["samples/simple"]

[features]
default = ["custom_cursor"]
custom_cursor = ["bevy/custom_cursor"]

[dependencies]
bevy = { git = "https://github.com/gehud/bevy.git", branch = "editor", features = [
    "debug",
    "track_location",
] }
bevy_mod_outline = { git = "https://github.com/gehud/bevy_mod_outline.git" }
rusqlite = { version = "0.39.0", features = ["bundled", "chrono"] }
chrono = "0.4.44"

[patch.crates-io]
bevy = { git = "https://github.com/gehud/bevy.git", branch = "editor" }

[patch.'https://github.com/gehud/bevy_editor']
bevy_editor = { path = "./" }
