[workspace]
resolver = "3"
members = ["samples/dev/editor", "samples/dev/runtime", "samples/dev/shared"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"

[package]
name = "bevy_editor"
version = "0.1.0"
edition = "2024"

[features]
editor = ["bevy/file_watcher", "bevy/asset_processor"]
default = ["documentation"]
documentation = ["bevy/reflect_documentation"]

[dependencies]
bevy = { version = "0.19.0", features = [
    "debug",
    "track_location",
    "jpeg",
    "serialize",
] }
smol_str = "0.2.2"
derive_more = "2.1.1"
bitflags = "2.11.1"

[patch.'https://github.com/gehud/bevy_editor']
bevy_editor = { path = "./" }
